spring:
  application:
    name: showcase-admin-tool
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      discovery:
        filter: "metadata.labels['spring-boot']"

  profiles:
    active:
      - secure

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    restart:
      enabled: true
      health:
    info:
      enabled: true

---

spring:
  profiles: secure
  security:
    user:
      name: "user"
      password: "password"

---

spring:
  profiles: insecure