spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"
    kubernetes:
      discovery:
        filter: "metadata.labels['spring-boot']"
  profiles:
    active:
      - secure

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

---

spring:
  profiles: secure
  security:
    user:
      name: "user"
      password: "password"

---

spring:
  profiles: insecure